[project]
name = "learnmcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-groq>=0.3.5",
    "mcp-use>=1.3.3",
    "mcp[cli]>=1.10.1",
]
